### PR TITLE
Feat: custom hosts

### PR DESCRIPTION
**Pull request by herefishyfish**
Adjusted it to match the Swift/Flutter implementations.
@goenning you might need to verify this is working correctly, only tested it by passing the EU host to the init function.

### CODE REVIEW

**Comment by goenning** [comment]
It works, thanks again :) 

One thing I noticed is that if the request fails, the whole app crashes with `Failed to connect to localhost/127.0.0.1:1424`

Any way we could add some try/catch or whatever is the equivalent in Kotlin and just log the error?

**Comment by goenning** [comment]
also, does the data class support unordered optional params?

The InitOptions will definitely grow in future, so if someone wants to change the session timeout but not the host, would they be able to do something like:

`InitOptions(sessionTime: ...)`

Similar to Swift and Flutter basically

**Comment by herefishyfish** [comment]
> One thing I noticed is that if the request fails, the whole app crashes with Failed to connect to localhost/127.0.0.1:1424

Good catch, I'll look into this.

> also, does the data class support unordered optional params?

Yea, it would look something like: `InitOptions(sessionTime = 1000)`

**Comment by herefishyfish** [comment]
@goenning should be okay now, give it another whirl.

**Comment by goenning** [comment]
Thanks 👏

**Pull request merged**
